function dq = AngularVelocity_to_EulerRates(in1,in2)
%ANGULARVELOCITY_TO_EULERRATES
%    DQ = ANGULARVELOCITY_TO_EULERRATES(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Aug-2017 13:40:54

qx = in1(3,:);
qy = in1(2,:);
wx = in2(1,:);
wy = in2(2,:);
wz = in2(3,:);
t2 = cos(qx);
t3 = sin(qx);
t4 = cos(qy);
t5 = 1.0./t4;
t6 = sin(qy);
dq = [t5.*(t3.*wy+t2.*wz);t2.*wy-t3.*wz;t5.*(t4.*wx+t3.*t6.*wy+t2.*t6.*wz)];
