function w = EulerRates_to_AngularVelocity(in1,in2)
%EULERRATES_TO_ANGULARVELOCITY
%    W = EULERRATES_TO_ANGULARVELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    03-Aug-2017 13:40:54

dqx = in2(3,:);
dqy = in2(2,:);
dqz = in2(1,:);
qx = in1(3,:);
qy = in1(2,:);
t2 = sin(qx);
t3 = cos(qx);
t4 = cos(qy);
w = [dqx-dqz.*sin(qy);dqy.*t3+dqz.*t2.*t4;-dqy.*t2+dqz.*t3.*t4];
